// eslint-disable-next-line no-undef
module.exports = {
  content: ["./pages/**/*.{js,ts,jsx,tsx}", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "white-100": "#fefefeff",
        "white-70": "#fefefeb2",
        "white-40": "#fefefe66",
        "white-20": "#fefefe33",
        "white-10": "#fefefe19",
        "white-05": "#fefefe0c",
        "black-100": "#1c1b20ff",
        "black-70": "#605f63ff",
        "black-40": "#a4a4a6ff",
        "black-20": "#d2d1d2ff",
        "black-10": "#e8e8e9ff",
        "black-05": "#f4f4f4ff",
        info: "#3f84e5ff",
        "info-light": "#78a9edff",
        "info-lighter": "#d2e2f9ff",
        "info-dark": "#124387ff",
        "info-darker": "#081c38ff",
        "success-dark": "#267963ff",
        "success-darker": "#17493bff",
        success: "#3ab795ff",
        "success-light": "#b6e8daff",
        "success-lighter": "#e7f7f3ff",
        danger: "#fd777cff",
        "danger-lighter": "#ffe0e1ff",
        "danger-dark": "#fd6268ff",
        "danger-light": "#fea1a4ff",
        "danger-darker": "#1f0002ff",
        warning: "#ffe787ff",
        "warning-light": "#ffec9fff",
        "warning-lighter": "#fff9dfff",
        "warning-dark": "#dfb300ff",
        "warning-darker": "#604d00ff",
        "background-white": "#ffffffff",
        "background-yellow": "#fff9dfff",
        "background-beige": "#fffaf5ff",
      },
    },
  },
  plugins: [],
};
